theme: jekyll-theme-cayman
encoding: UTF-8

# Site settings
title: ar's homepage
SEOTitle: ar's homepage

description: "守望者的逃离"
keyword: "ar, CTF, OI"
url: "https://ar00.co"
baseurl: ""

# Sidebar settings
sidebar: true
# sidebar-about-description: ""
# sidebar-avatar:
# use absolute URL, seeing it's used in both / and ' /about/’

# SNS settings
RSS: false

# Google Analytics
google_analytics: UA-162814912-1
